FROM python:3.12-slim

RUN pip install --no-cache-dir \
    "streamlit>=1.40.1" \
    pydantic \
    pydantic-settings \
    requests

WORKDIR /app

COPY src/ui ./src/ui
COPY src/config.py ./src/config.py
COPY .streamlit .streamlit

EXPOSE 8501

CMD ["python", "-m", "streamlit", "run", "src/ui/streamlit_app.py"]